### ISSUE TITLE
在uniapp vue2的版块框架中无法进行视频会议

### ISSUE THREAD

**Issue by gufeng0719** [xylink-com/xy-uniapp-demo#1]
引用xy-mp-sdk 3.8.7版本，根据示例复制sdk放到wxcomponents中，能够通过第三方方式正常登录并加入会议室。在客户端中可以看到登录用户，但是在小程序界面中一直处于呼叫状态，无法触发对onRoomEvent事件的监听

**Comment by luojinghui** [comment]
@gufeng0719 
升级小程序sdk到3.9.0版本试试：https://openapi.xylink.com/common/meeting/doc/version?platform=miniprogram#hd232a38-jAdltjDI
